name: 'Setup mshell'
description: 'Install the mshell concatenative shell language'
inputs:
  version:
    description: 'Version to install (e.g., v0.1.0). Defaults to latest.'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      run: |
        case "${{ runner.os }}-${{ runner.arch }}" in
          Linux-X64)   echo "asset=linux_amd64" >> $GITHUB_OUTPUT ;;
          Linux-ARM64) echo "asset=linux_arm64" >> $GITHUB_OUTPUT ;;
          macOS-X64)   echo "asset=darwin_amd64" >> $GITHUB_OUTPUT ;;
          macOS-ARM64) echo "asset=darwin_arm64" >> $GITHUB_OUTPUT ;;
          Windows-X64) echo "asset=windows_amd64" >> $GITHUB_OUTPUT ;;
          *) echo "Unsupported platform: ${{ runner.os }}-${{ runner.arch }}" && exit 1 ;;
        esac

    - name: Download and install mshell
      shell: bash
      env:
        ACTION_REPO: ${{ github.action_repository }}
      run: |
        VERSION="${{ inputs.version }}"
        ASSET="${{ steps.platform.outputs.asset }}"

        if [ "$VERSION" = "latest" ]; then
          URL="https://github.com/${ACTION_REPO}/releases/latest/download/${ASSET}.tar.gz"
        else
          URL="https://github.com/${ACTION_REPO}/releases/download/${VERSION}/${ASSET}.tar.gz"
        fi

        mkdir -p "$HOME/.mshell/bin"
        curl -sL "$URL" | tar -xz -C "$HOME/.mshell/bin"

        # Create symlinks so both msh and mshell work
        cd "$HOME/.mshell/bin"
        if [ -f mshell ]; then
          ln -sf mshell msh
        elif [ -f msh ]; then
          ln -sf msh mshell
        elif [ -f mshell.exe ]; then
          cp mshell.exe msh.exe
        elif [ -f msh.exe ]; then
          cp msh.exe mshell.exe
        fi

        echo "$HOME/.mshell/bin" >> $GITHUB_PATH

        # std.msh is included in the release tarball, move it to a standard location
        mv "$HOME/.mshell/bin/std.msh" "$HOME/.mshell/std.msh"
        echo "MSHSTDLIB=$HOME/.mshell/std.msh" >> $GITHUB_ENV
