name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: mshell/go.sum

    - name: Build go
      run: cd mshell && go build -o mshell

    - name: Set Go PATH, MSHSTDLIB
      run: |
        realpath ./mshell >> "$GITHUB_PATH"
        printf "MSHSTDLIB=%s\n" "$(realpath ./lib/std.msh)" >> "$GITHUB_ENV"

    - name: Run Go unit tests
      run: cd mshell && go test -v

    - name: Test mshell end-to-end
      run:  cd tests && ./test.sh

    - name: Run awk example tests
      run: cd examples/awk && ./test.sh
