name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # - name: Setup .NET
      # uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: 8
    # - name: Build
      # run: dotnet build
    # - name: Set PATH
      # run: realpath ./mshell/bin/Debug/net8.0 > "$GITHUB_PATH"

    - name: Set up Go
      uses: actions/setup-go@v5

    # - name: Test Files
      # run: cd mshell/tests && ./test.sh

    - name: Build go
      run: cd mshell && go build -o mshell

    - name: Set Go PATH
      run: realpath ./mshell > "$GITHUB_PATH"

    - name: Test mshell-go
      run:  cd tests && ./test.sh
