name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Install GNU Parallel
      run: sudo apt-get install parallel
    - name: Build
      run: dotnet build
    - name: Set PATH
      run: realpath ./mshell/bin/Debug/net8.0 > "$GITHUB_PATH"
    - name: Test Files
      run: cd mshell/test && ./test.sh
